# Here is the swagger documentation for the API is supposed to be. As the exercise is explicitly asking for a 
# swagger documentation, I'm not implementing it so I can spend more time in other parts of the exercise.